# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AI技術の最新動向を知る
email: mygungnir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  AI・人工知能に関する論文や情報を載せていきます。
baseurl: "/reading-article" # the subpath of your site, e.g. /blog
url: "http://aiarticle.com" # the base hostname & protocol for your site
twitter_username: mygungnir
github_username:  mygungnir

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
